//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRCodeGeneratorDBEntities : DbContext
    {

        private static QRCodeGeneratorDBEntities _context;

        public static QRCodeGeneratorDBEntities GetContext()
        {
            if (_context == null) _context = new QRCodeGeneratorDBEntities();
            return _context;
        }

        public QRCodeGeneratorDBEntities()
            : base("name=QRCodeGeneratorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<GenerationsHistory> GenerationsHistory { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
    }
}
