//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerationsHistory
    {
        public int id_generation { get; set; }
        public Nullable<int> id_account { get; set; }
        public Nullable<System.DateTime> generationTime { get; set; }
        public string generationText { get; set; }
        public string image_path { get; set; }
        public Nullable<int> susoiciouslvl { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
